<?php

 return [
#index.php
'title_main'=>'Bixbite Web Wallet',
'title_login_in'=>'Login',
'title_create_new_wallet'=>'创建钱包',
#wall.php     
'title_balance'=>'平衡:',
'title_unlock_balance'=>'解锁平衡:',     
'title_send'=>'发送',
'title_transaction'=>'交易',
'title_addr_book'=>'地址簿',
'title_restore'=>'恢复',
'title_configure'=>'组态',
'title_exit'=>'出口',
'title_aply'=>'应用',
'title_copy_addr'=>'复制地址',
'title_addr_is_copy'=>'复制!',     
#send.php     
'title_select_name'=>'选择名称:',
'title_select_addr'=>'选择地址:',
'title_inpput_kol'=>'输入金额:',
'title_input_id'=>'输入ID（如果需要）:',
'title_small_send'=>'发送',     
'title_all'=>'所有',
'title_empty'=>'必填字段未填写!',     
'title_no_money'=>'不充足的资金！',
#transaction.php
'title_t_in_or_out'=>'进或出',
'title_t_date'=>'日期',
'title_t_amount'=>'量',
'title_t_hash'=>'交易 hash',
#address_book.php
'title_t_name'=>'名称',
'title_t_addr'=>'地址',
'title_t_paimentid'=>'PaimentID',     
'title_t_date_created'=>'创建日期',
'title_t_del'=>'删除',        
'title_add'=>'加',
'title_del'=>'删除',
'title_data_exist'=>'重复数据！',     
#restore.php
'title_not_restore'=>'你无法恢复多个地址！',     
'title_input_seed'=>'输入助记词：',
'title_create_web_wallet'=>'创建一个 web wallet',
'title_yes_restore'=>'恢复',          
'title_error'=>'错误!',
'title_26_words'=>'一定是26个字！',     
'title_incorrect'=>'辛博尔不正确！',
'title_wallet_sync'=>'恢复的钱包同步！',     
#create_users.php
'title_pass_no'=>'密码不匹配！',
#new_user.php
'title_account_already_exists'=>'用户名已经被注册',
'title_email_already_exists'=>'此电子邮件的帐户已存在!',
'title_login'=>'Login',
'title_passw'=>'密码',
'title_confirm'=>'确认',
'title_email'=>'Email',
#create_wallet.php     
'title_your_addr'=>'你的地址：',
'title_seed_phrase'=>'助记短语：',
'title_spend_key'=>'Private key:',
'title_view_key'=>'Public key:',
'title_start_wallet'=>'开始 wallet!',
'title_save_to_file'=>'保存到文件',
'title_seed_help'=>'使用此助记词，您可以随时恢复您的钱包. <b>保持安全！</b>',
'title_private_help'=>'法律和公钥是新钱包的主要密钥. <b>保持安全！</b>',
#new_pass.php
'title_help_re_pass'=>'要更改密码，请使用以下字段:',
'title_old_pass'=>'旧密码',
'title_new_pass'=>'新密码',
'title_re_new_pass'=>'重复新密码',
'title_change_pass'=>'更改',
'title_pass_changed'=>'密码已更改！',
'title_old_pass_incorrect'=>'旧密码无效！',
'title_pass_incorrect'=>'密码不匹配！',
#del_account.php
'title_warning_del_account'=>'帐户和所有数据都将被删除！',
'title_del_account'=>'删除帐户',
'title_not_del_account'=>'删除已取消！',
'title_send_private_email'=>'通过电子邮件发送种子',
#confirm.php
'title_confirm_pass'=>'输入确认码',
'title_confirm_submit'=>'确认',
'title_incorrect_confirm'=>'无效的确认码！',
'title_return_confirm'=>'将代码发送到邮件！',     
'title_account_confirm'=>'帐户已激活！',
'title_activated_account'=>'要激活您的帐户，请单击按钮',
'title_confirm_account'=>'确认邮件！',
'title_other_pass_confirm'=>'或输入此验证码',
'title_reg_wallet'=>'注册BixBite钱包',
#configure.php
'title_your_addr_qr'=>'您的钱包地址在QR码中:',   
'title_seed_send_email'=>'从种子短语恢复钱包的信息',
'title_send_secret_data'=>'关键信息，用于恢复的钱包',     
];
