<?php

 return [
#index.php
'title_main'=>'Bixbite Web Brieftasche',
'title_login_in'=>'Login',
'title_create_new_wallet'=>'Brieftasche erstellen',
#wall.php     
'title_balance'=>'Balance:',
'title_unlock_balance'=>'Unlock balance:',     
'title_send'=>'SENDEN',
'title_transaction'=>'TRANSAKTION',
'title_addr_book'=>'ADRESSBUCH',
'title_restore'=>'WIEDERHERSTELLEN',
'title_configure'=>'KONFIGURATION',
'title_exit'=>'AUSFAHRT',
'title_aply'=>'Bestätigen Sie',
'title_copy_addr'=>'Adresse kopieren',
'title_addr_is_copy'=>'Kopiert!',     
#send.php     
'title_select_name'=>'Wählen Sie den Namen:',
'title_select_addr'=>'Wählen Sie die Adresse aus:',
'title_inpput_kol'=>'Eingabemenge:',
'title_input_id'=>'Eingabe ID (wenn nötig):',
'title_small_send'=>'Senden',     
'title_all'=>'Alle',
'title_empty'=>'Pflichtfelder sind nicht ausgefüllt.!',     
'title_no_money'=>'Unzureichende Mittel!',
#transaction.php
'title_t_in_or_out'=>'Rein oder raus',
'title_t_date'=>'Datum',
'title_t_amount'=>'Menge',
'title_t_hash'=>'Transaktion hash',
#address_book.php
'title_t_name'=>'Name',
'title_t_addr'=>'Adresse',
'title_t_paimentid'=>'PaimentID',     
'title_t_date_created'=>'Erstelldatum',
'title_t_del'=>'Löschen',        
'title_add'=>'Hinzufügen',
'title_del'=>'Löschen',
'title_data_exist' => 'Duplizierung von Daten!',     
#restore.php
'title_not_restore'=>'Sie können nicht mehr als eine Adresse wiederherstellen.!',     
'title_input_seed'=>'Eingabe mnemonische Phrase:',
'title_create_web_wallet'=>'Erstellen Sie eine Web-Brieftasche',
'title_yes_restore'=>'Wiederherstellen',          
'title_error'=>'Error!',
'title_26_words'=>'Muss 26 Wörter sein!',     
'title_incorrect'=>'Falsches Simbol!',
'title_wallet_sync'=>'Wiederhergestellte Brieftasche synchronisieren!',     
#create_users.php
'title_pass_no'=>'Passwörter stimmen nicht überein!',
#new_user.php
'title_account_already_exists'=>'Konto existiert bereits',
'title_email_already_exists'=>'Ein Konto mit dieser E-Mail existiert bereits!',
'title_login'=>'Login',
'title_passw'=>'Passwort',
'title_confirm'=>'Bestätigen',
'title_email'=>'Email',
'title_small_pass'=>'Kleiner Pass!',
'title_return_main'=>'Zur Startseite zurückkehren',
#create_wallet.php     
'title_your_addr'=>'Deine Adresse:',
'title_seed_phrase'=>'Mnemonische Phrase:',
'title_spend_key'=>'Privat Schlüssel:',
'title_view_key'=>'Öffentlicher Schlüssel:',
'title_start_wallet'=>'Brieftasche starten!',
'title_save_to_file'=>'In Datei speichern',
'title_seed_help'=>'Mit dieser mnemonischen Phrase können Sie Ihre Brieftasche jederzeit wiederherstellen. <b>Sicher aufbewahren!</b>',
'title_private_help'=>'Rechtliche und öffentliche Schlüssel sind die wichtigsten geheimen Schlüssel für die neue Brieftasche.<b>Sicher aufbewahren!</b>',
#new_pass.php
'title_help_re_pass'=>'Verwenden Sie zum Ändern Ihres Passworts die folgenden Felder:',
'title_old_pass'=>'Altes Passwort:',
'title_new_pass'=>'Neues Passwort:',
'title_re_new_pass'=>'Wiederhole das neue Passwort:',
'title_change_pass'=>'Veränderung',
'title_pass_changed'=>'Passwort geändert!',
'title_old_pass_incorrect'=>'Ungültiges altes Passwort!',
'title_pass_incorrect'=>'Passwörter stimmen nicht überein!',
#del_account.php
'title_warning_del_account'=>'Konto und alle Daten werden gelöscht!',
'title_del_account'=>'Konto löschen',
'title_not_del_account'=>'Löschung abgebrochen!',
'title_send_private_email'=>'Seed per E-Mail senden',
#confirm.php
'title_confirm_pass'=>'Geben Sie den Bestätigungscode ein',
'title_confirm_submit'=>'Bestätigen',
'title_incorrect_confirm'=>'ungültiger Bestätigungscode!',
'title_return_confirm'=>'Senden Sie den Code an die Mail!',     
'title_account_confirm'=>'Konto aktiviert!',
'title_activated_account'=>'Um Ihr Konto zu aktivieren, klicken Sie auf die Schaltfläche:',
'title_confirm_account'=>'Bestätigungs-E-Mail!',
'title_other_pass_confirm'=>'Oder geben Sie diesen Bestätigungscode ein:',
'title_reg_wallet'=>'Registrieren Sie BixBite Brieftasche',
#configure.php
'title_your_addr_qr'=>'Ihre Brieftasche-Adresse im QR-Code:',   
'title_seed_send_email'=>'Informationen zum Wiederherstellen der Brieftasche aus den Phrasen',
'title_send_secret_data'=>'Wichtige Informationen für die Wiederherstellung des Geldbeutels',
];
