<?php

 return [
#index.php
'title_main'=>'Bixbite WebWallet',
'title_login_in'=>'Login',
'title_create_new_wallet'=>'Create wallet',
#wall.php     
'title_balance'=>'Balance:',
'title_unlock_balance'=>'Unlock balance:',     
'title_send'=>'SEND',
'title_transaction'=>'TRANSACTION',
'title_addr_book'=>'ADDRESS BOOK',
'title_restore'=>'RESTORE',
'title_configure'=>'CONFIGURATION',
'title_exit'=>'EXIT',
'title_aply'=>'Apply',
'title_copy_addr'=>'Copy address',
'title_addr_is_copy'=>'Copied!',     
#send.php     
'title_select_name'=>'Select name:',
'title_select_addr'=>'Select address:',
'title_inpput_kol'=>'Input amount:',
'title_input_id'=>'Input ID(if need):',
'title_small_send'=>'Send',     
'title_all'=>'All',
'title_empty'=>'Required fields are not filled!',     
'title_no_money'=>'Insufficient funds!',
#transaction.php
'title_t_in_or_out'=>'In or Out',
'title_t_date'=>'Date',
'title_t_amount'=>'Amount',
'title_t_hash'=>'Transaction hash',
#address_book.php
'title_t_name'=>'Name',
'title_t_addr'=>'Address',
'title_t_paimentid'=>'PaimentID',     
'title_t_date_created'=>'Date of creation',
'title_t_del'=>'Delete',        
'title_add'=>'Add',
'title_del'=>'Delete',
'title_data_exist' => 'Duplication of data!',
#restore.php
'title_not_restore'=>'You cannot recover more than one address.!',     
'title_input_seed'=>'Input mnemonic phrase:',
'title_create_web_wallet'=>'Create a web wallet',
'title_yes_restore'=>'Restore',          
'title_error'=>'Error!',
'title_26_words'=>'Must be 26 words!',     
'title_incorrect'=>'Incorrect simbol!',
'title_wallet_sync'=>'Restored wallet synchronize!',     
#create_users.php
'title_pass_no'=>'Passwords do not match!',
#new_user.php
'title_account_already_exists'=>'Account already exists',
'title_email_already_exists'=>'An account with this email is already exists!',
'title_login'=>'Login',
'title_passw'=>'Password',
'title_confirm'=>'Confirm',
'title_email'=>'Email',
'title_small_pass'=>'Small pass!',
'title_return_main'=>'Return to the homepage',
#create_wallet.php     
'title_your_addr'=>'Your address:',
'title_seed_phrase'=>'Mnemonic phrase:',
'title_spend_key'=>'Private key:',
'title_view_key'=>'Public key:',
'title_start_wallet'=>'Start wallet!',
'title_save_to_file'=>'Save to file',
'title_seed_help'=>'Using this mnemonic phrase you can always restore your wallet at any time. <b>Keep it safe!</b>',
'title_private_help'=>'Legal and public keys are the main secret keys for the new wallet. <b>Keep it safe!</b>',
#new_pass.php
'title_help_re_pass'=>'To change your password, use the following fields:',
'title_old_pass'=>'Old password:',
'title_new_pass'=>'New password:',
'title_re_new_pass'=>'Repeat new password:',
'title_change_pass'=>'Change',
'title_pass_changed'=>'Password changed!',
'title_old_pass_incorrect'=>'Invalid old password!',
'title_pass_incorrect'=>'Passwords do not match!',
#del_account.php
'title_warning_del_account'=>'Account and all data will be deleted!',
'title_del_account'=>'Delete account',
'title_not_del_account'=>'Deletion canceled!',
'title_send_private_email'=>'Send seed by email',
#confirm.php
'title_confirm_pass'=>'Enter confirmation code',
'title_confirm_submit'=>'Confirm',
'title_incorrect_confirm'=>'Invalid confirmation code!',
'title_return_confirm'=>'Send the code to the mail!',     
'title_account_confirm'=>'Account activated!',
'title_activated_account'=>'To activate your account, click on the button:',
'title_confirm_account'=>'Confirm email!',
'title_other_pass_confirm'=>'Or enter this verification code:',
'title_reg_wallet'=>'Register BixBite wallet',
#configure.php
'title_your_addr_qr'=>'Your wallet address in QR code:',   
'title_seed_send_email'=>'Information for restoring wallet from seed phrases',
'title_send_secret_data'=>'Key information for restoring the wallet',
];
