<?php

 return [
#index.php
'title_main'=>'Bixbite BilleteraWeb',
'title_login_in'=>'Login',
'title_create_new_wallet'=>'Crear billetera',
#wall.php     
'title_balance'=>'Saldo:',
'title_unlock_balance'=>'Desbloquear saldo:',     
'title_send'=>'ENVIAR',
'title_transaction'=>'TRANSACCION',
'title_addr_book'=>'DIRECTORIO',
'title_restore'=>'RESTAURAR',
'title_configure'=>'CONFIGURACION',
'title_exit'=>'SALIDA',
'title_aply'=>'Aplicar',
'title_copy_addr'=>'Copiar direccion',
'title_addr_is_copy'=>'Copiado!',     
#send.php     
'title_select_name'=>'Seleccionar nombre:',
'title_select_addr'=>'Seleccionar direccion:',
'title_inpput_kol'=>'Cantidad de entrada:',
'title_input_id'=>'ID de entrada (si es necesario):',
'title_small_send'=>'Enviar',     
'title_all'=>'Todo',
'title_empty'=>'Los campos requeridos no se llenan.!',     
'title_no_money'=>'Fondos insuficientes!',
#transaction.php
'title_t_in_or_out'=>'Dentro o fuera',
'title_t_date'=>'Fecha',
'title_t_amount'=>'Cantidad',
'title_t_hash'=>'Transaccion hash',
#address_book.php
'title_t_name'=>'Nombre',
'title_t_addr'=>'Direccion',
'title_t_paimentid'=>'ID de pago',     
'title_t_date_created'=>'Fecha de creacion',
'title_t_del'=>'Eliminar',        
'title_add'=>'Anadir',
'title_del'=>'Eliminar',
'title_data_exist' => 'Duplicación de datos',     
#restore.php
'title_not_restore'=>'No se puede recuperar mas de una direccion..!',     
'title_input_seed'=>'Frase mnemotecnica de entrada:',
'title_create_web_wallet'=>'Crear una billetera web',
'title_yes_restore'=>'Restaurar',          
'title_error'=>'Error!',
'title_26_words'=>'Debe tener 26 palabras!',     
'title_incorrect'=>'Simbol incorrecto!',
'title_wallet_sync'=>'Sincronizar billetera restaurada!',     
#create_users.php
'title_pass_no'=>'Las contrasenas no coinciden!',
#new_user.php
'title_account_already_exists'=>'La cuenta ya existe',
'title_email_already_exists'=>'Esta cuenta ya existe.!',
'title_login'=>'Login',
'title_passw'=>'Contrasena',
'title_confirm'=>'Confirmar',
'title_email'=>'Email',
'title_small_pass'=>'Pequeno pase!',
'title_return_main'=>'Vuelve a la pagina inicial',
#create_wallet.php     
'title_your_addr'=>'Tu direccion:',
'title_seed_phrase'=>'Frase mnemonica:',
'title_spend_key'=>'Clave privada:',
'title_view_key'=>'Clave publica:',
'title_start_wallet'=>'Empezar billetera!',
'title_save_to_file'=>'Guardar en archivo',
'title_seed_help'=>'Usando esta opcion siempre puedes restaurar tu billetera en cualquier momento. <b>Mantenlo seguro!</b>',
'title_private_help'=>'Claves secretas para la nueva billetera.. <b>Mantenlo seguro!</b>',
#new_pass.php
'title_help_re_pass'=>'Para cambiar su contrasena, use los siguientes campos:',
'title_old_pass'=>'Contrasena anterior:',
'title_new_pass'=>'Nueva contrasena:',
'title_re_new_pass'=>'repita la nueva contrasena:',
'title_change_pass'=>'Cambio',
'title_pass_changed'=>'contrasena cambiada!',
'title_old_pass_incorrect'=>'Contrasena antigua invalida!',
'title_pass_incorrect'=>'Las contrasenas no coinciden!',
#del_account.php
'title_warning_del_account'=>'La cuenta y todos los datos seran eliminados.!',
'title_del_account'=>'Borrar cuenta',
'title_not_del_account'=>'Cancelacion cancelada!',
'title_send_private_email'=>'Enviar semillas por correo electronico',
#confirm.php
'title_confirm_pass'=>'Introducir el codigo de confirmacion',
'title_confirm_submit'=>'Confirmar',
'title_incorrect_confirm'=>'Codigo de confirmacion invalido!',
'title_return_confirm'=>'Enviar el codigo al correo.!',     
'title_account_confirm'=>'Cuenta activada!',
'title_activated_account'=>'Para activar su cuenta, haga clic en el boton:',
'title_confirm_account'=>'Confirmar correo electronico!',
'title_other_pass_confirm'=>'O ingresa este codigo de verificacion:',
'title_reg_wallet'=>'Registrar billetera BixBite',
#configure.php
'title_your_addr_qr'=>'Su direccion de billetera en codigo QR:',   
'title_seed_send_email'=>'Informacion para restaurar cartera de frases semilla.',
'title_send_secret_data'=>'Información clave para restaurar la billetera.',
];
