<?php

 return [
#index.php
'title_main'=>'Bixbite Portefeuille Web',
'title_login_in'=>'Login',
'title_create_new_wallet'=>'Créer un portefeuille',
#wall.php     
'title_balance'=>'SOLDE:',
'title_unlock_balance'=>'Débloquer le solde:',     
'title_send'=>'ENVOYER',
'title_transaction'=>'TRANSACTION',
'title_addr_book'=>'CARNET D\'ADRESSES',
'title_restore'=>'RESTAURER',
'title_configure'=>'CONFIGURATION',
'title_exit'=>'SORTIE',
'title_aply'=>'Appliquer',
'title_copy_addr'=>'Copier l\'adresse',
'title_addr_is_copy'=>'Copié!',     
#send.php     
'title_select_name'=>'Sélectionnez le nom:',
'title_select_addr'=>'Sélectionnez l\'adresse:',
'title_inpput_kol'=>'Montant d\'entrée:',
'title_input_id'=>'ID d\'entrée (si besoin):',
'title_small_send'=>'Envoyer',     
'title_all'=>'Tout',
'title_empty'=>'Les champs obligatoires ne sont pas remplis.!',     
'title_no_money'=>'Fonds insuffisants!',
#transaction.php
'title_t_in_or_out'=>'Dedans ou dehors',
'title_t_date'=>'la date',
'title_t_amount'=>'Montant',
'title_t_hash'=>'Transaction hash',
#address_book.php
'title_t_name'=>'le nom',
'title_t_addr'=>'Adresse',
'title_t_paimentid'=>'PaimentID',     
'title_t_date_created'=>'Date de création',
'title_t_del'=>'Dépiler',        
'title_add'=>'Ajouter',
'title_del'=>'Dépiler',
'title_data_exist' => 'Duplication de données!',     
#restore.php
'title_not_restore'=>'Vous ne pouvez pas récupérer plus d\'une adresse.!',     
'title_input_seed'=>'Phrase mnémonique d\'entrée:',
'title_create_web_wallet'=>'Créer un portefeuille Web',
'title_yes_restore'=>'Restaurer',          
'title_error'=>'Erreur!',
'title_26_words'=>'Doit être 26 mots!',     
'title_incorrect'=>'Simbol incorrect!',
'title_wallet_sync'=>'Le portefeuille restauré se synchronise!',     
#create_users.php
'title_pass_no'=>'Les mots de passe ne correspondent pas!',
#new_user.php
'title_account_already_exists'=>'Le compte existe déjà',
'title_email_already_exists'=>'Un compte avec cet email existe déjà!',
'title_login'=>'Login',
'title_passw'=>'Mot de passe',
'title_confirm'=>'Confirmer',
'title_email'=>'Email',
'title_small_pass'=>'Petit mot de passe!',
'title_return_main'=>'Retour à la page d\'accueil',
#create_wallet.php     
'title_your_addr'=>'Votre adresse:',
'title_seed_phrase'=>'Phrase mnémonique:',
'title_spend_key'=>'Private key:',
'title_view_key'=>'Public key:',
'title_start_wallet'=>'Portefeuille de départ!',
'title_save_to_file'=>'Enregistrer dans le fichier',
'title_seed_help'=>'En utilisant cette phrase mnémonique, vous pouvez toujours restaurer votre portefeuille à tout moment. <b>Garde-le en sécurité!</b>',
'title_private_help'=>'Les clés légales et publiques sont les clés secrètes principales du nouveau portefeuille. <b>Garde-le en sécurité!</b>',
#new_pass.php
'title_help_re_pass'=>'Pour changer votre mot de passe, utilisez les champs suivants:',
'title_old_pass'=>'Ancien mot de passe:',
'title_new_pass'=>'Nouveau mot de passe:',
'title_re_new_pass'=>'Répété le nouveau mot de passe:',
'title_change_pass'=>'Changement',
'title_pass_changed'=>'Mot de passe changé!',
'title_old_pass_incorrect'=>'Ancien mot de passe invalide!',
'title_pass_incorrect'=>'Les mots de passe ne correspondent pas!',
#del_account.php
'title_warning_del_account'=>'Le compte et toutes les données seront supprimés!',
'title_del_account'=>'Supprimer le compte',
'title_not_del_account'=>'Suppression annulée!',
'title_send_private_email'=>'Envoyer des semences par email',
#confirm.php
'title_confirm_pass'=>'Entrer le code de confirmation',
'title_confirm_submit'=>'Confirmer',
'title_incorrect_confirm'=>'code de confirmation invalide!',
'title_return_confirm'=>'Envoyez le code à l\'e-mail!',     
'title_account_confirm'=>'Compte activé!',
'title_activated_account'=>'Pour activer votre compte, cliquez sur le bouton:',
'title_confirm_account'=>'Confirmez votre e-mail!',
'title_other_pass_confirm'=>'Ou entrez ce code de vérification:',
'title_reg_wallet'=>'Enregistrez le portefeuille BixBite',
#configure.php
'title_your_addr_qr'=>'Votre adresse de portefeuille dans le code QR:',   
'title_seed_send_email'=>'Informations pour la restauration du portefeuille à partir de phrases clés',
'title_send_secret_data'=>'Informations clés pour restaurer le portefeuille',
];
