<?php

 return [
    #index.php
    'title_main'=>'Bixbite веб кошелёк',
    'title_login_in'=>'Войти',
    'title_create_new_wallet'=>'Создать кошелёк',
    #wall.php     
    'title_balance'=>'Баланс:',
    'title_unlock_balance'=>'Доступный баланс:',     
    'title_send'=>'ОТПРАВИТЬ',
    'title_transaction'=>'ТРАНЗАКЦИИ',
    'title_addr_book'=>'АДРЕСНАЯ КНИГА',
    'title_restore'=>'ВОССТАНОВЛЕНИЕ',
    'title_configure'=>'КОНФИГУРАЦИЯ',
    'title_exit'=>'ВЫХОД',
    'title_aply'=>'Применить',
    'title_copy_addr'=>'Копировать адрес',
    'title_addr_is_copy'=>'Адрес скопирован!',     
    #send.php     
    'title_select_name'=>'Выберите имя получателя:',
    'title_select_addr'=>'Или введите адрес:',
    'title_inpput_kol'=>'Введите количество:',
    'title_input_id'=>'Введите платёжный ID(при необходимости):',
    'title_small_send'=>'Отправить',     
    'title_all'=>'Все',
    'title_empty'=>'Не заполнены обязательные поля!',     
    'title_no_money'=>'Недостаточно средств!',
    #transaction.php
    'title_t_in_or_out'=>'Входящая или исходящая',
    'title_t_date'=>'Дата',
    'title_t_amount'=>'Количество',
    'title_t_hash'=>'Хеш транзакции',
    #address_book.php
    'title_t_name'=>'Имя',
    'title_t_addr'=>'Адрес',
    'title_t_paimentid'=>'Платёжный идентификатор',     
    'title_t_date_created'=>'Дата создания',
    'title_t_del'=>'Удаление',        
    'title_add'=>'Добавить',
    'title_del'=>'Удалить',
    'title_data_exist'=>'Дублирование данных!',
    #restore.php
    'title_not_restore'=>'Вы не можете восстановить более одного адреса!',     
    'title_input_seed'=>'Введите мнемоническую фразу:',
    'title_create_web_wallet'=>'Создание веб кошелька',
    'title_yes_restore'=>'Восстановить',          
    'title_error'=>'Ошибка!',
    'title_26_words'=>'Должно быть 26 слов!',     
    'title_incorrect'=>'Некорректные символы!',
    'title_wallet_sync'=>'Восстановленный кошелёк синхронизируется!',     
    #create_users.php
    'title_pass_no'=>'Пароли не совпадают!',
    #new_user.php
    'title_account_already_exists'=>'Аккаунт уже существует',
    'title_email_already_exists'=>'Учётная запись с данным почтовым ящиком уже присутствует в системе!',
    'title_login'=>'Логин',
    'title_passw'=>'Пароль',
    'title_confirm'=>'Подтверждение',
    'title_email'=>'Электронная почта',
    'title_small_pass'=>'Слишком короткий пароль!',
    'title_return_main'=>'Вернуться на главную страницу',
    #create_wallet.php     
    'title_your_addr'=>'Ваш адрес:',
    'title_seed_phrase'=>'Мнемоническая фраза:',
    'title_spend_key'=>'Приватный ключ:',
    'title_view_key'=>'Публичный ключ:',
    'title_start_wallet'=>'Начать работу с кошельком!',
    'title_save_to_file'=>'Сохранить в файл',
    'title_seed_help'=>'Используя эту мнемоническую фразу Вы сможете всегда восстанавить свой кошелек в любое время. <b>Храните их в безопасности!</b>',
    'title_private_help'=>'Праватный и публичный ключи являются основными секретными ключами для нового кошелька. <b>Храните их в безопасности!</b>',
    #new_pass.php
    'title_help_re_pass'=>'Для смены пароля воспользуйтесь следующими полями:',
    'title_old_pass'=>'Старый пароль:',
    'title_new_pass'=>'Новый пароль:',
    'title_re_new_pass'=>'Повторите новый пароль:',
    'title_change_pass'=>'Сменить',
    'title_pass_changed'=>'Пароль изменён!',
    'title_old_pass_incorrect'=>'Неверный старый пароль!',
    'title_pass_incorrect'=>'Пароли не совпадают!',
    #del_account.php
    'title_warning_del_account'=>'Будет произведено удаление аккаунта и всех данных о нём!',
    'title_del_account'=>'Удалить аккаунт',
    'title_not_del_account'=>'Удаление отменено!',
    'title_send_private_email'=>'Выслать seed&keys на почту',
    #confirm.php
    'title_confirm_pass'=>'Введите код подтверждения',
    'title_confirm_submit'=>'Подтвердить',
    'title_incorrect_confirm'=>'Неверный код подтверждения!',
    'title_return_confirm'=>'Отправить код на почту!',     
    'title_account_confirm'=>'Учётная запись активирована!',
    'title_activated_account'=>'Для активации аккаунта, нажмите на кнопку:',
    'title_confirm_account'=>'Подтвердить email!',
    'title_other_pass_confirm'=>'Или введите этот код подтверждения:',
    'title_reg_wallet'=>'Регистрация кошелька BixBite',
    #configure.php
    'title_your_addr_qr'=>'Ваш адресс кошелька в QR коде:',   
    'title_seed_send_email'=>'Информация для восстановления кошелька из seed фразы',
    'title_send_secret_data'=>'Ключевая информация для восстановления кошелька',
];
